### ISSUE TITLE
Can't find it from Settings > Install

### ISSUE THREAD

**Issue by pertrai1** [algolia/atom-autocomplete-module-import#10]
When I search for this package I am not able to find it from the install. Does this have to be manually installed?

**Comment by rayrutjes** [comment]
Hey @pertrai1 ,

The package is published on the official repository: https://atom.io/packages/autocomplete-module-import

You can find it by searching for: `autocomplete-module-import` in from the "install" tab of the settings:

![image](https://user-images.githubusercontent.com/5570853/27884581-23e60cc4-61d5-11e7-9958-d66f6a109ca8.png)

Let me know if that works for you.

We would love to bump it higher in the results, but given the plugin is fairly new, it is displayed a bit far for now.

Let me know if you have any tip to better rank it ;)

**Comment by pertrai1** [comment]
👍  @rayrutjes. Thanks for the help and screenshot. I have found it now and installing.
