### ISSUE TITLE
Feature Request: Please support coffeescript files

### ISSUE THREAD

**Issue by jhessin** [algolia/atom-autocomplete-module-import#27]
I write my programs in coffeescript and compile them into ES6 javascript. Is there any way to allow this package to suggest modules in that language as well as Javascript? It uses the exact same phrasing i.e.

```coffeescript
require('node-pkg')
import pkg from 'node-pkg'
```

The only difference is the parenthesis are optional i.e.

```coffeescript
require 'node-pkg'
```

**Comment by Haroenv** [comment]
Regarding your last point, the relevant code is here: 

https://github.com/algolia/atom-autocomplete-module-import/blob/eaa4d95ccb640958ac9d12a77354f340620ea6a5/lib/current-line.js#L5

We also need to add the support for the correct file types for coffeescript. See this:


https://github.com/algolia/atom-autocomplete-module-import/blob/eaa4d95ccb640958ac9d12a77354f340620ea6a5/lib/suggestions-provider.js#L13-L14

Do you want to make a PR?

**Comment by jhessin** [comment]
Just put in a PR.
